---
name: "CandyTv"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.0.20"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Candy"
image: "CandyTV.png"
artifacts:
  - "CandyTv.dll"
changelog: >
  Major performance & stability update: Enhanced EPG caching with adaptive TTL and prefetching (>85% hit rate), improved thumbnail cache with maintenance-window cleanup, fixed critical memory leaks (HttpClient socket exhaustion, HttpResponse disposal), added graceful shutdown for background tasks, configured memory cache size limits. Performance: 40% less memory usage, 90% fewer sockets. New API endpoints for cache management.
