---
name: "CandyTv"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.0.23"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Candy"
image: "CandyTV.png"
artifacts:
  - "CandyTv.dll"
changelog: >
  Restored direct Xtream stream URLs (with embedded username/password) so playback works again in cases where clients expect credentials in the path. The proxy/token experiment is disabled for now to guarantee compatibility with player workflows that perform multiple requests (HEAD/RANGE) per stream.
