---
name: "CandyTv"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.0.25"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Candy"
image: "CandyTV.png"
artifacts:
  - "CandyTv.dll"
changelog: >
  Further stabilises live playback by reusing Xtream’s `direct_source` URLs (including provider-specific parameters) and logging upstream HTTP statuses so restreams no longer terminate immediately even with strict providers.
