---
name: "CandyTv"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.0.22"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Candy"
image: "CandyTV.png"
artifacts:
  - "CandyTv.dll"
changelog: >
  Fixed compatibility issues with Jellyfin’s shared metadata cache. The plugin now relies on the host’s default memory cache configuration so third-party providers (e.g. TMDb image lookups) no longer throw “Cache entry must specify a value for Size” errors while using CandyTv alongside other plugins.
