---
name: "CandyTv"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.0.24"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Candy"
image: "CandyTV.png"
artifacts:
  - "CandyTv.dll"
changelog: >
  Fixes live channel playback by adding the Xtream `/live` segment and container extension to stream URLs before restreaming. Clients now receive valid credential-bearing paths, eliminating the immediate connection tear-down seen in 0.0.23.
